title: Maxim N. Brodmerkel  # You can add your name here


description: PhD in Biochemistry. # Fix hyphenation 

show_downloads: true # Fix spelling

theme: jekyll-theme-minimal 

plugins:
  - jekyll-seo-tag # Add SEO plugin

email: maxim.brodmerkel@gmail.com # Allow visitors to contact you
